# kindly generated by appropriated Rails generator
Mailjet.configure do |config|
  config.api_key = '764f9e2e048bd23342ae1010dd9bab0a'
  config.secret_key = 'b4a01804c5c8abb9517c3e97044c5b7e'
  config.default_from = ''
  # Mailjet API v3.1 is at the moment limited to Send API.
  # We’ve not set the version to it directly since there is no other endpoint in that version.
  # We recommend you create a dedicated instance of the wrapper set with it to send your emails.
  # If you're only using the gem to send emails, then you can safely set it to this version.
  # Otherwise, you can remove the dedicated line into config/initializers/mailjet.rb.
  config.api_version = 'v3.1'
end
